Increase robustness to support Android NDK 16+
backtrace-labs/libbun pull request #3
Opened 2021-08-05 22:41 UTC by rqbacktrace

2021-08-09 15:25 UTC, pkhuong requested changes

2021-08-09 15:25 UTC, pkhuong commented on src/bun_cpp_utils.cpp
> +struct deleter
the struct's name should reflect what it does (it calls `free(2)`), not only how it's used.

2021-08-09 15:25 UTC, pkhuong commented on src/bun_cpp_utils.cpp
> +	void operator() (T data) {
This should be a const method, and we want to make sure `data` is a pointer, so that's `void operator()(T* data) const`

2021-08-09 15:25 UTC, pkhuong commented on src/bun_cpp_utils.cpp
> +template<typename T>
The definition should be in an anonymous namespace.

2021-08-09 15:25 UTC, pkhuong commented on src/bun_cpp_utils.cpp
> +	void operator() (T data) {
We could also move the template to the operator, `template <typename T> void operator()(T *data) const`, and not have to repeat the deleted type in `unique_ptr`.

2021-08-09 15:25 UTC, pkhuong commented on src/bun_cpp_utils.cpp
> +	char* result_cstr = result.get();
Don't do that: stashing the value of `unique_ptr::get` in variables makes it easier to have dangling pointers. We should instead call `get` everywhere we need a raw pointer.

2021-08-09 15:25 UTC, pkhuong commented on src/bun_utils.c
> +	{
Is that the brace style for bun? I see `if () {` everywhere else.

2021-08-09 15:25 UTC, pkhuong commented on src/bun_utils.c
>  	fd = open(name, O_CREAT | O_TRUNC | O_CLOEXEC | O_RDWR, S_IRUSR | S_IWUSR);
are we sure this code works for `O_TMPFILE` ? For `O_TMPFILE`, `name` should specify a directory, not a filename.

2021-08-09 15:25 UTC, pkhuong commented on src/bun_utils.c
>  	if (unlink(name) == -1)
why do we unlink with `O_TMPFILE` ?

2021-08-09 15:25 UTC, pkhuong commented on src/bun_utils.c
> +	fd = -1;
why do we want to leak `fd` when we inject failures?

2021-09-14 15:10 UTC, closed without merging

2021-09-14 15:10 UTC, rqbacktrace commented
@KrzaQ already addressed these issues, thank you!